---
- hosts: lapoli.isprambiente.it
  name: First test

  tasks:
          - name: First test
            command: "systemctl status sshd.service | egrep -i "active" | wc -l"
            register: result

          - name: Check
            assert:
              that:
                   - 1 in result.stdout_lines
