---
- hosts: lapoli.isprambiente.it
  name: First test

  tasks:
          - name: First test
            command: "ls -l | wc -l"
            register: result
            debug:
              var: result

          - name: Check
            assert:
              that:
                   - 1 in result.stdout_lines
