---
- hosts: lapoli.isprambiente.it
  name: First test

  tasks:
          - name: First test
            shell: "systemctl status sshd.service | egrep -i 'active'"
            register: result
          - name: debug
            debug:
              var: result
              verbosity: 2

          - name: Check
            assert:
              that:
                   - 1 in result.stdout_lines
