
---
- name: Garantire accesso sicuro
  hosts: localhost

  tasks:

    - name: set varibles
      set_fact:
        ansible_become_password: "tobeseto"

    - name: Check sshd
      shell: "systemctl status sshd.service | egrep -i 'active' | wc -l"
      register: result

    - name: debug result
      debug:
        var: result

    - name: Check telnetd deamon
      #become: true
      shell: "ps - aux | grep telnet | wc -l"
      register: result1

    - name: debug result1
      debug:
        var: result1

    - name: Check results
      assert:
        that:
             - "'1' in result.stdout_lines"
             - "'0' in result1.stdout_lines"
