---
- hosts: lapoli.isprambiente.it
  name: Garantire accesso sicuro

  tasks:
    - name: Command to excecute
      shell: "systemctl status sshd.service | egrep -i 'active' | wc -l"
      register: result

    #- name: debug
    #  debug:
    #    var: result

    - name: Check results
      assert:
        that:
             - "'1' in result.stdout_lines"
